general {
    output_format = "i3bar"
    separator = " | "
    colors = true
    color_good = "#00ff00"
    color_degraded = "#0000ff"
    color_bad = "#ff0000"

}

order += "wireless wlan0"
order += "ethernet enp0s31f6"
order += "battery 1"
order += "disk /home/"
order += "disk /"
order += "time"

wireless wlan0 {
    format_up = "W: (%quality at %essid, %bitrate ) %ip "
}

ethernet enp0s31f6 {
    format_up = " E: %ip (%speed) "
    format_down = " E: down "
}

battery 1 {
    format = " %status %percentage "
    integer_battery_capacity = true
    format_percentage = "%.02f%s "
    status_chr = " Carregando"
    status_full = " Carregado"
    path = /sys/class/power_supply/BAT1/uevent
}

disk "/home/" {
    format = " home: %avail "
}

disk "/" {
    format = " root: %avail "
}

time {
    format = " %d-%m-%Y %H:%M:%S "
}
